
# Site settings

url: "http://www.herodrigues.me"
baseurl: ""
google-tracking-id: "UA-68009625-1"
force-https: False

syntax-highlight: True

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

web-app-mode: True

# Icons for Chrome Web App mode https://developer.chrome.com/multidevice/android/installtohomescreen
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

#############
# HTML Head #
#############

author: "Herinson Rodrigues"
lang: "en"
title: "@herodrigues"
favicon: "/img/favicon.ico"
description: "Blog and website of Herinson Rodrigues"
keywords: "rodrigues, herinson, web, developer, brazil"

################
# Intro layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/opera.jpg"
me-img: "/img/me.png"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: False
loop-count: 1 # Set False for infinite loop, or set any number for finite loop.
type-speed: 4
start-delay: 2000
delete-delay: 50000
lines: # You can add HTML Tags in the Text
  - text: "Hi! My name is Herinson Rodrigues"
  - text: "I'm a Web/Desktop developer"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "herodrigues"

###############
# Life Events #
###############

events:
  - image: "/img/timeline/ifpi.png"
    date: "February 2006 - November 2009"
    description: "Technician in Information Technology at [Federal Institute of Piaui](http://floriano.ifpi.edu.br/
) - Brazil"
  - image: "/img/timeline/inspectocat.jpg"
    date: "April 2006 - Today"
    description: "Started coding"
  - image: "/img/timeline/uft.jpg"
    date: "August 2010 - Today"
    description: "Bachelor in Computer Science at [Federal University of Tocantins](http://www.uft.edu.br) - Brazil"
  - image: "/img/timeline/collabocats.jpg"
    date: "June 2012 - Today"
    description: "Started contributing to Open Source projects on [Github](http://github.com)"
  - image: "/img/timeline/ford-trucks.jpg"
    date: "July 2012 - December 2012"
    description: "Backend developer at [Ford Disbrava Trucks](http://www.ford.disbrava.com.br/)"     
  - image: "/img/timeline/mq.png"
    date: "July 2013 - December 2014"
    description: "Student exchange program at [Macquarie University](http://mq.edu.au) - Australia"
  - image: "/img/timeline/eduft.png"
    date: "August 2015 - November 2015"
    description: "Full stack developer at [EdUFT](http://ww1.uft.edu.br/index.php/institucional/orgaos-complementares/editora-universitaria-eduft)"    
  - image: "/img/timeline/58phases.png"
    date: "October 2015 - Today"
    description: "Web developer at [58phases](http://58phases.com)"     

# First image of the Career timeline
timeline-img: "/img/timeline/default.png"

##################
# Contact layout #
##################

email: "herinson.br@uft.edu.br"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/herodriguess"
  - title: "github"
    url: "https://github.com/herodrigues"
  - title: "stack-overflow"
    url: "https://stackoverflow.com/users/4913642/herodrigues"
  - title: "flask"
    url: "http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4325996A4"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
