# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: mathjax
disqus: herodrigues
google_analytics: UA-68009625-1
title: Herinson Rodrigues
permalink: pretty

#defaults:
#  -
#    scope:
#      path: "" # empty string for all files
#    values:
#      title: "@herodrigues"

description: Keep learning
author:
  name: Herinson Rodrigues
  email: herinson.br@uft.edu.br
  github: herodrigues
  # stackoverflow: 4913642/herodrigues
  lattes: "8487847834781115"
  # researcherid: "D-5273-2017"
  bio: Bachelor in Computer Science, <br> web developer by accident<br> and science lover

images:
  favicon: "/assets/ico/favicon.ico"
  profile: "https://avatars1.githubusercontent.com/u/1832537?v=3&s=150"

publications_path: publications
categories_path: categories
education_path: education

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

# localization
languages: ["en", "pt"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

plugins:
  - jekyll-paginate
